---
tmp_dir: '[% c("tmp_dir") %]'
appname_marfile: i2p-browser
appname_bundle_osx: I2PBrowser
appname_bundle_linux: i2p-browser
appname_bundle_win32: i2pbrowser-install
appname_bundle_win64: i2pbrowser-install-win64
releases_dir: [% path(c('output_dir')) %]/signed
#download:
#    archive_url: https://archive.torproject.org/tor-package-archive/i2pbrowser
#    gpg_keyring: ../../keyring/i2pbrowser.gpg
#    bundles_url: https://dist.torproject.org/i2pbrowser
#    mars_url: https://cdn.torproject.org/aus1/i2pbrowser
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32:
        - WINNT_x86-gcc3
        - WINNT_x86-gcc3-x86
        - WINNT_x86-gcc3-x64
    win64: WINNT_x86_64-gcc3-x64
    osx32: Darwin_x86-gcc3
    osx64: Darwin_x86_64-gcc3
channels:
    [% pc('firefox', 'var/i2pbrowser_update_channel') %]: [% c("var/i2pbrowser_version") %]
versions:
    [% c("var/i2pbrowser_version") %]:
[% IF c("var/create_unsigned_incrementals") -%]
        releases_dir: [% path(c('output_dir')) %]/unsigned
[% END -%]
        platformVersion: [% pc('firefox', 'var/firefox_platform_version') %]
#        detailsURL: https://blog.torproject.org/new-release-i2p-browser-[% c("var/i2pbrowser_version") FILTER remove('\.') %]
        incremental_from:
[% FOREACH v IN c("var/i2pbrowser_incremental_from") -%]
          - [% v %]
[% END -%]
        migrate_archs:
          osx32: osx64
        migrate_langs:
            pt-PT: pt-BR
        minSupportedInstructionSet: SSE2
        osx32:
            minSupportedOSVersion: 13.0.0
        osx64:
            minSupportedOSVersion: 13.0.0
        win32:
            minSupportedOSVersion: 6.1
        win64:
            minSupportedOSVersion: 6.1
mar_compression: xz
#htaccess_rewrite_rules:
#    alpha: |
#        # bug 26569: Redirect pre-8.0a9 alpha users to a separate update directory
#        RewriteRule ^[^/]+/8\.0a[12345678]/.* https://aus1.torproject.org/i2pbrowser/update_pre8.0a9/alpha/$0 [last]
#        RewriteRule ^[^/]+/[4567]\..*/.* https://aus1.torproject.org/i2pbrowser/update_pre8.0a9/alpha/$0 [last]
#    release: |
#        # bug 26570: Redirect pre-8.0 stable users to a separate update directory
#        RewriteRule ^[^/]+/[4567]\..*/.* https://aus1.torproject.org/i2pbrowser/update_pre8.0/release/$0 [last]
